import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {emptyPointSelection,normalizePointSelection,serializePointSelection,sourceFrameSize,processingFrameSize,processingPreviewGeometry,coverCropRect,previewPointInSource,pointFromPointer,previewFrameTime,clearPointsForMedia,installPointPickers,syncPointPickers} from '../public/point-picker.js';
import {controlField} from '../public/workflow-controls.js';
import {catalogEditor,prepareCatalogSnapshot} from '../public/catalog-ui.js';
import {catalogSubmission} from '../public/catalog-submission.js';

const close=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-6,`${actual} != ${expected}`);
assert.deepEqual(processingFrameSize(1920,1080,1280,32),{width:1280,height:736});
assert.deepEqual(processingFrameSize(1080,1920,1280,32),{width:736,height:1280});
assert.deepEqual(processingFrameSize(1001,700,1280,32),{width:1280,height:896});
assert.deepEqual(processingFrameSize(1920,1080,1024,32),{width:1024,height:576});
assert.deepEqual(sourceFrameSize(1001,700,8),{width:1000,height:704});
assert.deepEqual(processingFrameSize(1001,700,1280,32,8),{width:1280,height:928});
assert.deepEqual(processingFrameSize(2,1,1,32),{width:32,height:32});
assert.throws(()=>processingFrameSize(0,1080),/无效/);
assert.throws(()=>processingFrameSize(1920,1080,NaN),/无效/);
assert.throws(()=>processingFrameSize(1920,1080,1280,0),/无效/);

const crop=coverCropRect(1920,1080,1280,736);
close(crop.x,20.869565217391255);close(crop.y,0);close(crop.width,1878.2608695652175);close(crop.height,1080);
const center=previewPointInSource({x:.5,y:.5},crop);close(center.x,960);close(center.y,540);
const twoStep=processingPreviewGeometry(1919,1080,{longSide:1280,sourceMultiple:8,multiple:32});
assert.deepEqual(twoStep.source,{width:1920,height:1080});assert.deepEqual(twoStep.target,{width:1280,height:736});
close(twoStep.crop.y,.28125);close(twoStep.crop.height,1079.4375);
assert.ok(twoStep.framePercent.width>100);close(twoStep.framePercent.height,100);
assert.notEqual(twoStep.crop.height,coverCropRect(1919,1080,1280,736).height,'opposite successive crops cannot collapse into a single cover operation');
const twoStepCenter=previewPointInSource({x:.5,y:.5},twoStep.crop);close(twoStepCenter.x,959.5);close(twoStepCenter.y,540);
const point=pointFromPointer(180,132,{left:20,top:40,width:640,height:368});
assert.deepEqual(point,{x:.25,y:.25});
const sourcePoint=previewPointInSource(point,crop);close(sourcePoint.x,490.4347826086956);close(sourcePoint.y,270);
assert.deepEqual({x:Math.floor(point.x*1280),y:Math.floor(point.y*736)},{x:320,y:184},'coordinates use the processed, cropped frame');
assert.deepEqual(pointFromPointer(-1,500,{left:0,top:0,width:200,height:100}),{x:0,y:1});
assert.throws(()=>pointFromPointer(1,1,{left:0,top:0,width:0,height:100}),/准备/);
assert.equal(previewFrameTime({frameRate:24},48,10),2);
assert.equal(previewFrameTime({},0,10),0,'the unskipped first frame needs no guessed fps');
assert.throws(()=>previewFrameTime({},1,10),/帧率/);
assert.throws(()=>previewFrameTime({frameRate:24},240,10),/超出/);
assert.throws(()=>previewFrameTime({frameRate:24},.5,10),/整数/);

const selected={positive:[{x:.25,y:.25}],negative:[{x:1,y:0}]};
assert.deepEqual(normalizePointSelection(serializePointSelection(selected)),selected);
assert.equal(serializePointSelection(),'{"positive":[],"negative":[]}');
assert.deepEqual(normalizePointSelection({positive:[{x:1/3,y:2/3}],negative:[]}),{positive:[{x:.333333,y:.666667}],negative:[]});
assert.throws(()=>normalizePointSelection('not-json'));
assert.throws(()=>normalizePointSelection({positive:[],negative:[],private_points:[1]}),/格式/);
for(const bad of [{x:-.1,y:.5},{x:1.1,y:.5},{x:NaN,y:.5},{x:Infinity,y:.5},{x:'0.5',y:.5}])assert.throws(()=>normalizePointSelection({positive:[bad],negative:[]}),/画面/);
assert.equal(normalizePointSelection({positive:Array.from({length:12},()=>({x:.5,y:.5})),negative:Array.from({length:12},()=>({x:.1,y:.1}))}).negative.length,12);
assert.throws(()=>normalizePointSelection({positive:Array.from({length:13},()=>({x:.5,y:.5})),negative:[]}),/最多/);
assert.throws(()=>normalizePointSelection({positive:[],negative:Array.from({length:13},()=>({x:.5,y:.5}))}),/最多/);

const schemas=JSON.parse(readFileSync(new URL('../public/workflow-interfaces.json',import.meta.url),'utf8')).workflows;
const catalog=JSON.parse(readFileSync(new URL('../public/local-catalog.json',import.meta.url),'utf8')).workflows;
const w={...catalog.find(w=>w.id==='local-card-51'),interface:schemas['local-card-51'],catalogConnected:true,catalogConnection:{adapter:'generic',validation:'structural-verified'}};
const f=w.interface.controls.find(f=>f.kind==='points');
assert.equal(f.mediaSlotId,'1084');assert.equal(f.previewRecipe.longSideControlId,'1105:value');assert.equal(f.previewRecipe.longSide,1280);assert.equal(f.previewRecipe.frameRate,24);assert.equal(f.previewRecipe.sourceMultiple,8);assert.equal(f.previewRecipe.skipControlId,'1084:skip_first_frames');
assert.deepEqual(normalizePointSelection(f.value),emptyPointSelection(),'public defaults must never inherit private sample selections');
const draft={prompt:'点选测试',refs:[],catalogValues:{},catalogTexts:{},catalogSeedModes:{}};
const blank=controlField(draft,f);assert.match(blank,/先添加原视频/);assert(!blank.includes('<video'),'an absent source must not use unrelated media');
const bound={...draft,refs:[{kind:'video',catalogSlot:'other-slot',src:'unrelated.mp4'},{kind:'video',catalogSlot:'1084',src:'assets/award-film-10s.mp4'}],catalogValues:{[f.id]:serializePointSelection(selected)}};
const markup=controlField(bound,f);assert.match(markup,/assets\/award-film-10s.mp4/);assert(!markup.includes('unrelated.mp4'));
assert.equal((catalogEditor(w,bound).match(/data-catalog-field="1095:points"/g)||[]).length,1,'one input writes the production binding');
assert.match(markup,/data-point-clear/);assert.match(markup,/data-point-mode="negative"/);assert.match(markup,/tabindex="0"/);
assert.throws(()=>prepareCatalogSnapshot(w,structuredClone(draft)),/至少点选一个/);
const snapshot=prepareCatalogSnapshot(w,structuredClone(bound));
assert.deepEqual(normalizePointSelection(catalogSubmission(w,snapshot).catalog_values[f.id]),selected,'the clicked points reach the generic submission by id');
const independent={id:'unrelated:points',kind:'points',mediaSlotId:'other-slot'};
const withOther={...w,interface:{...w.interface,controls:[...w.interface.controls,independent]}};
const reset={catalogValues:{[f.id]:serializePointSelection(selected),[independent.id]:serializePointSelection(selected),'1105:value':1280}};
clearPointsForMedia(reset,withOther,'1084');
assert.deepEqual(normalizePointSelection(reset.catalogValues[f.id]),emptyPointSelection());assert.deepEqual(normalizePointSelection(reset.catalogValues[independent.id]),selected);assert.equal(reset.catalogValues['1105:value'],1280);

// Exercise the production event handlers with a minimal DOM facade. The app's
// normal input commit re-enters sync, so a frame change must not dispatch twice.
const events=new Map(),writes=[],style={},layer={innerHTML:''},error={textContent:'',hidden:true},clear={disabled:false},count={textContent:''},loading={hidden:false},sourceFrame={style:{}},cursor={hidden:true,style:{}};
const modeButtons=['positive','negative'].map(mode=>({dataset:{pointMode:mode},setAttribute(){},closest:selector=>selector==='[data-point-picker]'?box:selector==='button[data-point-mode]'?modeButtons.find(button=>button.dataset.pointMode===mode):null}));
const input={value:serializePointSelection(emptyPointSelection()),dataset:{catalogField:f.id},closest:selector=>selector==='[data-point-picker]'?box:null};
const longSide={value:'1280',validity:{valid:true},dataset:{catalogField:'1105:value'}},skip={value:'0',validity:{valid:true},dataset:{catalogField:'1084:skip_first_frames'},closest:selector=>selector==='[data-point-picker]'?null:selector==='.catalog-editor'?scope:null};
const stage={dataset:{},style,focus(){},querySelector:selector=>selector==='[data-point-cursor]'?cursor:null,getBoundingClientRect:()=>({left:20,top:40,width:640,height:368}),closest:selector=>selector==='[data-point-picker]'?box:selector==='[data-point-stage]'?stage:null};
const video={videoWidth:638,videoHeight:360,readyState:2,currentTime:0,duration:4,seeking:false,pause(){},closest:()=>box};
const nodes={'[data-catalog-field]':input,'[data-point-layer]':layer,'[data-point-error]':error,'[data-point-clear]':clear,'[data-point-count]':count,'[data-point-stage]':stage,'[data-point-loading]':loading,'[data-point-source-frame]':sourceFrame,video};
const scope={querySelectorAll:selector=>selector==='[data-catalog-field]'?[longSide,skip,input]:selector==='[data-point-picker]'?[box]:[]};
const box={dataset:{pointMode:'positive',pointRecipe:JSON.stringify(f.previewRecipe)},querySelector:selector=>nodes[selector]||null,querySelectorAll:selector=>selector==='button[data-point-mode]'?modeButtons:[],matches:()=>false,closest:selector=>selector==='.catalog-editor'?scope:null};
const eventRoot={matches:()=>false,querySelectorAll:selector=>selector==='[data-point-picker]'?[box]:[],addEventListener:(name,handler)=>{if(!events.has(name))events.set(name,[]);events.get(name).push(handler);}};
const fire=(type,target,extra={})=>{for(const handler of events.get(type)||[])handler({target,...extra});};
input.dispatchEvent=()=>{writes.push(input.value);assert.ok(writes.length<100,'input synchronization must not recurse');fire('input',input);syncPointPickers(eventRoot);};
installPointPickers(eventRoot);
assert.equal(stage.dataset.pointWidth,1280);assert.equal(stage.dataset.pointHeight,736);assert.equal(stage.dataset.pointReady,'true');
fire('click',stage,{clientX:180,clientY:132});assert.deepEqual(normalizePointSelection(input.value).positive,[{x:.25,y:.25}]);
fire('click',modeButtons[1]);fire('click',stage,{clientX:500,clientY:316});assert.deepEqual(normalizePointSelection(input.value).negative,[{x:.75,y:.75}]);
const remove={dataset:{pointRemove:'negative',pointIndex:'0'},closest:selector=>selector==='[data-point-picker]'?box:selector==='[data-point-remove]'?remove:null};
fire('click',remove);assert.equal(normalizePointSelection(input.value).negative.length,0);
const beforeFrameChange=writes.length;skip.value='48';fire('input',skip);
assert.equal(video.currentTime,2);assert.equal(writes.length,beforeFrameChange+1,'changing frame clears once despite app sync re-entry');assert.deepEqual(normalizePointSelection(input.value),emptyPointSelection());
fire('keydown',stage,{key:'Enter',preventDefault(){}});assert.equal(normalizePointSelection(input.value).negative.length,1,'keyboard point selection shares the active mode');
const clearButton={closest:selector=>selector==='[data-point-picker]'?box:selector==='[data-point-clear]'?clearButton:null};
fire('click',clearButton);assert.deepEqual(normalizePointSelection(input.value),emptyPointSelection());
assert.ok(sourceFrame.style.width.endsWith('%'));assert.equal(stage.style.aspectRatio,'1280 / 736');

console.log(JSON.stringify({processedFrameGeometry:'passed',coverCoordinates:'passed',knownFrameSeek:'passed',normalizedLimitAndValidation:'passed',sourceSlotIdentity:'passed',emptySourceGate:'passed',submission:'passed',mediaReplacementReset:'passed',pointerAndKeyboardEvents:'passed',frameChangeReentrantCommit:'passed'}));
