import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {mergeWorkspaceSnapshots} from '../public/workspace-merge.js';
import {openStorage,readState,writeState} from '../public/storage.js';
import {referenceProvenance,mergeReferenceSnapshots,matchesLiveRecord,reconcileLiveJobs,sameLiveJob} from '../public/live-history.js';
import {effectiveCatalogInterface,catalogHistorySnapshot,catalogReferenceSnapshots} from '../public/catalog-submission.js';

const clone=value=>structuredClone(value);
const original={sessions:[{id:'s61',scope:'wf:local-card-51',title:'已有草稿',draft:{prompt:'原描述',refs:[],catalogValues:{}},jobs:[{id:'live-old',remoteId:'server-old',started:1,status:'running',snapshot:{prompt:'任务原描述',refs:[]},outputs:[{id:'old-output',src:'/old.png'}]}]}],active:'s61',nextSession:66,nextJob:40,collections:[],reviewSeeded:false,preferences:{theme:'dark'}};
const tabA=clone(original),tabB=clone(original);
tabA.sessions[0].draft={prompt:'刚编辑的区域',refs:[{id:'图片1',originalAssetId:'original',maskAssetId:'mask'}],catalogValues:{strength:2}};
tabA.sessions.push({id:'s-uuid-a',scope:'wf:local-card-15',title:'新局部编辑',draft:{prompt:'真实验收',refs:[]},jobs:[]});tabA.active='s-uuid-a';tabA.collections=[{id:'collection-a',name:'新分类'}];
tabB.sessions[0].jobs[0].status='done';tabB.sessions[0].jobs[0].outputs[0].src='/new.png';
let merged=mergeWorkspaceSnapshots(original,tabA,original);merged=mergeWorkspaceSnapshots(merged,tabB,original);
assert.equal(merged.sessions.length,2,'an old polling tab cannot erase an unknown new session');assert.equal(merged.active,'s-uuid-a');
assert.deepEqual(merged.sessions[0].draft,tabA.sessions[0].draft,'job polling owns no unchanged draft');assert.equal(merged.sessions[0].jobs[0].status,'done');assert.equal(merged.collections[0].name,'新分类');assert.deepEqual(merged.preferences,{theme:'dark'});
const hidden=clone(tabB);hidden.sessions[0].historyHidden=true;merged=mergeWorkspaceSnapshots(merged,hidden,tabB);assert.equal(merged.sessions[0].historyHidden,true);assert.deepEqual(merged.sessions[0].draft,tabA.sessions[0].draft);
assert.equal(mergeWorkspaceSnapshots(merged,{...tabB,sessions:[]},tabB).sessions.length,2,'absence never means deletion');
const userEdited=clone(tabB);userEdited.sessions[0].draft.prompt='另一个标签明确修改';assert.equal(mergeWorkspaceSnapshots(merged,userEdited,tabB).sessions[0].draft.prompt,'另一个标签明确修改','explicit edits of one shared draft use last-writer semantics');
const refsOnly=clone(original);refsOnly.sessions[0].draft.refs=[{id:'图片1',assetId:'new-reference'}];let disjoint=mergeWorkspaceSnapshots(merged,refsOnly,original);assert.equal(disjoint.sessions[0].draft.prompt,'刚编辑的区域','replacing a reference owns no unchanged prompt');assert.deepEqual(disjoint.sessions[0].draft.refs,refsOnly.sessions[0].draft.refs);
const separateParameter=clone(original);separateParameter.sessions[0].draft.catalogValues.other=3;disjoint=mergeWorkspaceSnapshots(disjoint,separateParameter,original);assert.deepEqual(disjoint.sessions[0].draft.catalogValues,{strength:2,other:3},'independent parameter IDs keep separate write authority');assert.equal(disjoint.sessions[0].draft.refs[0].assetId,'new-reference');
const changedOutput=clone(tabB);changedOutput.sessions[0].jobs[0].outputs[0].removedAt=123;changedOutput.sessions[0].jobs[0].outputs[0].published=true;
let retained=mergeWorkspaceSnapshots(merged,changedOutput,tabB);const poll=clone(tabB);poll.sessions[0].jobs[0].outputs[0].src='/latest.png';retained=mergeWorkspaceSnapshots(retained,poll,tabB);
assert.equal(retained.sessions[0].jobs[0].outputs[0].removedAt,123);assert.equal(retained.sessions[0].jobs[0].outputs[0].published,true);assert.equal(retained.sessions[0].jobs[0].outputs[0].src,'/latest.png');
const beforeRunning=clone(original);beforeRunning.sessions[0].jobs[0].status='submitting';assert.equal(mergeWorkspaceSnapshots(retained,original,beforeRunning).sessions[0].jobs[0].status,'done','older server replies cannot resurrect a finished attempt');
assert.equal(original.sessions[0].draft.prompt,'原描述','merging never mutates another tab baseline');

// IDB test surface schedules complete readwrite transactions serially, as IndexedDB does.
// Execute the production get/merge/put function, rather than mocking writeState itself.
let persisted=clone(original),transactionQueue=Promise.resolve();const transactions=[];
const db={transaction(name,mode){const ops=[],tx={error:null,objectStore(){return {get(key){const request={};ops.push(()=>{request.result=clone(persisted);request.onsuccess?.();});return request;},put(value,key){const request={};ops.push(()=>{persisted=clone(value);request.result=key;request.onsuccess?.();});return request;}};},abort(){throw new Error('unexpected abort');}};transactions.push({name,mode,ops});transactionQueue=transactionQueue.then(()=>new Promise(resolve=>queueMicrotask(()=>{for(let i=0;i<ops.length;i++)ops[i]();tx.oncomplete?.();resolve();})));return tx;}};
globalThis.indexedDB={open(){const request={};queueMicrotask(()=>{request.result=db;request.onsuccess?.();});return request;}};
await openStorage();
const app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),start=app.indexOf('function saveRef('),end=app.indexOf('async function initializeWorkspace(',start),saveSource=app.slice(start,end);
function tab(snapshot){const context=vm.createContext({state:{sessions:clone(snapshot.sessions),active:snapshot.active},workspace:{collections:clone(snapshot.collections),reviewSeeded:snapshot.reviewSeeded},nextSession:snapshot.nextSession,nextJob:snapshot.nextJob,storageReady:true,structuredClone,writeState,toast(){assert.fail('save unexpectedly failed');},Promise});vm.runInContext(saveSource,context);vm.runInContext('workspaceSaveBaseline=workspaceSnapshot()',context);return context;}
const a=tab(original),b=tab(original);a.state.sessions=clone(tabA.sessions);a.state.active=tabA.active;a.workspace.collections=clone(tabA.collections);b.state.sessions=clone(tabB.sessions);
await Promise.all([a.saveWorkspace(),b.saveWorkspace()]);let reread=await readState();
assert.equal(reread.sessions.length,2);assert.equal(reread.sessions.find(s=>s.id==='s61').draft.prompt,'刚编辑的区域');assert.equal(reread.sessions.find(s=>s.id==='s61').jobs[0].status,'done');assert.equal(reread.active,'s-uuid-a');assert.equal(reread.collections[0].name,'新分类');
assert(transactions.filter(t=>t.mode==='readwrite').every(t=>t.ops.length===2),'the read and merged write occur in one IDB transaction');
const c=tab(reread);c.state.sessions[0].draft.prompt='另一标签的新输入';await c.saveWorkspace();await a.saveWorkspace();reread=await readState();assert.equal(reread.sessions[0].draft.prompt,'另一标签的新输入','an unchanged repeated save owns no old fields');
const queuedFirst=a.saveWorkspace();a.state.sessions[0].draft.prompt='后续明确输入';const queuedSecond=a.saveWorkspace();await Promise.all([queuedFirst,queuedSecond]);assert.equal((await readState()).sessions[0].draft.prompt,'后续明确输入');

const makeStart=app.indexOf('function makeSession('),makeEnd=app.indexOf('\nmakeSession();',makeStart),routeStart=app.indexOf('function route('),routeEnd=app.indexOf('\nconst workflow=',routeStart);
const ids=vm.createContext({state:{sessions:[]},newDraft:()=>({refs:[]}),crypto:globalThis.crypto,location:{hash:'#session/s61'},decodeURIComponent});vm.runInContext(app.slice(makeStart,makeEnd)+'\n'+app.slice(routeStart,routeEnd),ids);
const newA=ids.makeSession(),newB=ids.makeSession();assert.match(newA.id,/^s-[0-9a-f-]{36}$/);assert.notEqual(newA.id,newB.id);assert.equal(ids.route().id,'s61','old short-ID routes remain readable');
const completeStart=app.indexOf('function complete('),completeEnd=app.indexOf('\nfunction tickJobs(',completeStart),demo=vm.createContext({DEMO_DURATION:1000,images:['/one.png','/two.png','/three.png'],film:{src:'/sample.mp4',poster:'/poster.png'},encodeURIComponent});vm.runInContext(app.slice(completeStart,completeEnd),demo);
for(const id of ['j1','j2','j-55c1ab95-b4fe-4b50-b8d3-0d92d221a9b1']){const job={id,started:0,snapshot:{type:'image',count:2}};demo.complete(job);assert.equal(job.outputs.length,2);assert(job.outputs.every(o=>demo.images.includes(o.src)),'UUID demo jobs must select a valid built-in image');if(id==='j1')assert.equal(job.outputs[0].src,'/one.png','legacy demo output selection stays unchanged');}
for(const type of ['video','text']){const job={id:'j-55c1ab95-b4fe-4b50-b8d3-0d92d221a9b1',started:0,snapshot:{type,count:1}};demo.complete(job);assert.equal(job.outputs[0].type,type);assert(job.outputs[0].src);}
// A server import and optimistic row are the same attempt only with an exact
// server ID/token. The old live-<server ID> alias must converge after polling.
const serverId='a'.repeat(32),otherServerId='b'.repeat(32),pairedId='c'.repeat(64),originalId='d'.repeat(64);
const receipt={id:serverId,request_token:'exact-request-token',workflow_id:'history-tool',status:'done',stage:'已完成',started:100,ended:200,prompt:'相同提示词',settings:{},catalog_values:{'1:seed':711051},catalog_texts:{},catalog_assets:{source:pairedId},outputs:[{id:serverId+'o0',type:'image',src:'/actual-result.png'}],references:[{id:pairedId,kind:'image',name:'reference-1.png',src:'/api/assets/'+pairedId+'/file',catalogSlot:'source',original_asset_id:originalId,original_src:'/api/assets/'+originalId+'/file',original_available:true,annotation_mode:'mask'}]};
const optimistic={id:'live-original-uuid',real:true,remoteId:serverId,token:receipt.request_token,started:100,status:'running',stage:'正在提交到算力卡',snapshot:{prompt:receipt.prompt,catalogValues:{'1:seed':711051},refs:[{id:'图片1',kind:'image',name:'原始蓝图.png',catalogSlot:'source',serverAssetId:pairedId,src:'/api/assets/'+pairedId+'/file',originalAssetId:'local-original',maskAssetId:'local-mask',annotationMode:'mask'}]},outputs:[]};
const namedVideo={kind:'video',name:'shirt-continuous-1s.mp4',assetId:'exact-local-source',serverAssetId:pairedId,catalogSlot:'1084'},genericVideo={kind:'video',name:'reference-1.mp4',serverAssetId:pairedId,catalogSlot:'1084'};
assert.equal(mergeReferenceSnapshots([namedVideo],[genericVideo])[0].name,'shirt-continuous-1s.mp4');
assert.equal(mergeReferenceSnapshots([{...namedVideo,serverAssetId:undefined}],[genericVideo])[0].name,'shirt-continuous-1s.mp4','an immutable input slot can retain the local name before a server ID has been written');
const changedVideo=mergeReferenceSnapshots([{...namedVideo,originalAssetId:'old-original',serverAssetId:originalId}],[genericVideo])[0];assert.equal(changedVideo.name,'reference-1.mp4');assert.equal(changedVideo.originalAssetId,undefined,'an explicitly different uploaded input cannot inherit a slot predecessor name or provenance');
assert.equal(mergeReferenceSnapshots([namedVideo],[{...genericVideo,name:'server-custom-video.mp4'}])[0].name,'server-custom-video.mp4','real server names are not treated as upload placeholders');
assert.equal(mergeReferenceSnapshots([],[genericVideo])[0].name,'reference-1.mp4','server-only history has no local name to invent');
assert.equal(mergeReferenceSnapshots([{...namedVideo,name:'reference-1.mp4'}],[genericVideo],[{id:'exact-local-source',name:'shirt-continuous-1s.mp4'}])[0].name,'shirt-continuous-1s.mp4','an existing exact asset ID can recover a previously overwritten display name');
assert.equal(mergeReferenceSnapshots([{...namedVideo,name:'reference-1.mp4'}],[genericVideo],[{id:'different-local-source',name:'not-the-same-video.mp4'}])[0].name,'reference-1.mp4');
assert.equal(mergeReferenceSnapshots([{kind:'video',name:'unproven-positional-name.mp4'}],[{...genericVideo,catalogSlot:undefined}])[0].name,'reference-1.mp4','name preservation requires an explicit asset ID or slot, not position/name similarity');
const ghost={id:'live-'+serverId,real:true,status:'running',stage:'正在提交到算力卡',started:100,snapshot:{prompt:receipt.prompt,refs:[]},outputs:[]};
assert(sameLiveJob(optimistic,ghost));assert(matchesLiveRecord(ghost,receipt));
const duplicateState={...clone(original),sessions:[{id:'original-session',draft:{refs:[]},jobs:[clone(optimistic)]},{id:'import-session',draft:{refs:[]},jobs:[clone(ghost)]}]};
const repairedStored=mergeWorkspaceSnapshots(duplicateState,clone(duplicateState),clone(duplicateState));assert.equal(repairedStored.sessions.flatMap(s=>s.jobs).length,1);assert.equal(repairedStored.sessions[0].jobs[0].id,optimistic.id);assert.equal(repairedStored.sessions[0].jobs[0].snapshot.refs[0].originalAssetId,'local-original');
const imported={...clone(ghost),remoteId:serverId,status:'done',ended:200,snapshot:{catalogValues:{'1:seed':424242},refs:[{id:'图片1',kind:'image',serverAssetId:pairedId,src:'/api/assets/'+pairedId+'/file'}]},outputs:receipt.outputs};
const newRich={...clone(optimistic),status:'done',ended:200};
const importedFirst=mergeWorkspaceSnapshots({...clone(original),sessions:[{id:'same-session',draft:{refs:[]},jobs:[imported]}]}, {...clone(original),sessions:[{id:'same-session',draft:{refs:[]},jobs:[newRich]}]}, {sessions:[]});
assert.equal(importedFirst.sessions[0].jobs.length,1);assert.equal(importedFirst.sessions[0].jobs[0].snapshot.refs[0].originalAssetId,'local-original','an import saved first cannot erase a later proven original identity');
const olderOptimistic={sessions:[{id:'one',jobs:[clone(optimistic),clone(imported)]}]};reconcileLiveJobs(olderOptimistic.sessions);assert.equal(olderOptimistic.sessions[0].jobs[0].snapshot.catalogValues['1:seed'],424242,'a completed server import owns the actual seed even when the richer optimistic row is retained');assert.equal(olderOptimistic.sessions[0].jobs[0].snapshot.refs[0].originalAssetId,'local-original');
const historyTool={id:'history-tool',catalogConnected:true,output:'image',catalogConnection:{adapter:'generic'},interface:{texts:[{id:'prompt',role:'prompt'}],controls:[],media:[{id:'source',kind:'image'}]}};
const independent={...clone(optimistic),id:'live-independent-uuid',remoteId:otherServerId,token:'other-token',snapshot:clone(optimistic.snapshot)};
let pollSaves=0;const pollContext=vm.createContext({publicPreview:false,production:true,liveCatalog:[historyTool],workflows:[historyTool],workspace:{assets:[]},state:{sessions:[{id:'original-session',scope:'wf:history-tool',draft:{refs:[]},jobs:[clone(optimistic),clone(ghost),independent]}]},referenceProvenance,mergeReferenceSnapshots,matchesLiveRecord,reconcileLiveJobs,effectiveCatalogInterface,catalogHistorySnapshot,catalogReferenceSnapshots,catalogValuesFromSettings:()=>({}),newDraft:type=>({type,refs:[]}),liveApi:async()=>[receipt],Date,crypto:globalThis.crypto,scheduleSave(){pollSaves++;},sidebar(){},$:()=>null,dialog:{open:false},route:()=>({name:'home'})});
const mergeStart=app.indexOf('function mergeCatalogJob('),mergeEnd=app.indexOf('\nasync function rerunLive(',mergeStart),pollStart=app.indexOf('let livePollBusy='),pollEnd=app.indexOf('\nasync function cancelLive(',pollStart);
vm.runInContext(app.slice(mergeStart,mergeEnd)+'\n'+app.slice(pollStart,pollEnd),pollContext);await pollContext.syncLiveJobs();
const afterPoll=pollContext.state.sessions.flatMap(s=>s.jobs),completed=afterPoll.find(j=>j.remoteId===serverId);assert.equal(afterPoll.length,2,'equal prompt/seed with a different attempt identity remains distinct');assert.equal(completed.id,optimistic.id);assert.equal(completed.status,'done');assert.equal(completed.outputs.length,1);assert.equal(completed.snapshot.refs[0].originalAssetId,'local-original');assert.equal(completed.snapshot.refs[0].originalServerAssetId,originalId);assert.equal(completed.snapshot.refs[0].annotationMode,'mask');assert.equal(completed.token,receipt.request_token);assert.equal(afterPoll.find(j=>j.remoteId===otherServerId).status,'running');assert.equal(pollSaves,1);
assert.equal(completed.snapshot.refs[0].name,'原始蓝图.png','production polling plus duplicate reconciliation retains the original local display name');
await pollContext.syncLiveJobs();assert.equal(pollContext.state.sessions.flatMap(s=>s.jobs).length,2,'later polls cannot reimport the removed ghost');assert.equal(pollSaves,1,'unchanged provenance/status does not trigger repeated saves');
const legacyRefJob={id:'legacy-input-history',snapshot:{refs:clone(optimistic.snapshot.refs)},outputs:[]};pollContext.mergeLiveJob(legacyRefJob,{...receipt,workflow_id:'legacy-tool'});assert.equal(legacyRefJob.snapshot.refs[0].originalAssetId,'local-original');assert.equal(legacyRefJob.snapshot.refs[0].maskAssetId,'local-mask');assert.equal(legacyRefJob.snapshot.refs[0].originalServerAssetId,originalId,'legacy video references also consume proven server originals without replacing local identities');
assert.equal(legacyRefJob.snapshot.refs[0].name,'原始蓝图.png');
console.log(JSON.stringify({uuidSessionsAndLegacyRoutes:'passed',uuidDemoOutputs:'passed',actualSaveFunctionAndIdbTransaction:'passed',unknownSessionRetention:'passed',backgroundDraftProtection:'passed',independentDraftAndParameterFields:'passed',jobOutputFieldMerging:'passed',softHistoryHiding:'passed',collectionsAndPreferences:'passed',sameFieldExplicitLastWriter:'documented',queuedSnapshots:'passed',exactAttemptGhostReconciliation:'passed',actualPollAndServerProvenance:'passed',importFirstOriginalIdentity:'passed',completedReceiptSeedAuthority:'passed'}));
