import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {similarWorkflows,originalReference,restoredInputs,matchesWork,taskCover} from '../public/workflow-experience.js';
const catalog=JSON.parse(readFileSync(new URL('../public/local-catalog.json',import.meta.url),'utf8')).workflows;
const schemas=JSON.parse(readFileSync(new URL('../public/workflow-interfaces.json',import.meta.url),'utf8')).workflows;
const workflows=catalog.map(w=>({...w,interface:schemas[w.id]}));
const outfit=workflows.find(w=>w.id==='local-card-3');
assert.deepEqual(similarWorkflows(outfit,workflows).map(w=>w.id),['local-card-3','local-card-73']);
const refs=[{kind:'image',src:'/original.png',catalogSlot:'551'},{kind:'image',src:'/clothes.png',catalogSlot:'547'}];
const field=outfit.interface.controls.find(f=>f.kind==='seed');
const snapshot={workflowId:outfit.id,catalogLive:true,prompt:'换成蓝色衣服',negative:'文字',refs,catalogValues:{[field.id]:424254},catalogSeedModes:{}};
const before=structuredClone(snapshot),restored=restoredInputs(snapshot,outfit);
assert.deepEqual(restored.refs,refs);
assert.equal(restored.catalogSeedModes[field.id],'fixed');
assert.equal(restored.catalogValues[field.id],424254);
restored.refs[0].src='/edited-draft.png';
assert.deepEqual(snapshot,before,'editing a restored draft must never change historical input');
const o={type:'image',src:'/result.png'},j={real:true,status:'done',started:1000,snapshot};
assert.equal(originalReference(j,o).src,'/original.png');
assert.ok(taskCover(outfit,[{o,j}]).includes('/original.png'));
assert.ok(taskCover(outfit,[{o,j}]).includes('/result.png'));
assert.doesNotThrow(()=>taskCover(outfit,[{o,j:{...j,snapshot:{...snapshot,refs:[]}}}]));
assert.ok(!taskCover(outfit,[{o,j:{...j,real:false}}]).includes('/result.png'),'demo output must not be presented as a real cover');
const now=Date.now(),row={o,j:{...j,started:now-8*86400000}};
assert.equal(matchesWork(row,'蓝色','all',now,workflows),true);
assert.equal(matchesWork(row,'换衣','all',now,workflows),false);
assert.equal(matchesWork(row,'服装','all',now,workflows),true);
assert.equal(matchesWork(row,'','7',now,workflows),false);
assert.equal(matchesWork(row,'','30',now,workflows),true);
console.log(JSON.stringify({similarTasks:'passed',originalInputRestoration:'passed',fixedSeedRestoration:'passed',immutableHistory:'passed',coverEvidence:'passed',searchAndTime:'passed'}));
